FROM python:3.12.2-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# 작업 디렉토리 설정
WORKDIR /app

# 소스 코드 추가
COPY . /app


# 필요한 패키지 설치
RUN pip install --no-cache-dir -r requirements.txt

RUN python manage.py migrate

# 컨테이너 실행 시 실행할 명령어 설정
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]