# Generated by Django 5.0.4 on 2024-04-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='attraction_image',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
