# Generated by Django 5.0.4 on 2024-04-26 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_fullname', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=20)),
                ('line_number', models.SmallIntegerField()),
                ('line_name', models.CharField(max_length=10)),
                ('direction1', models.CharField(max_length=50)),
                ('direction2', models.CharField(max_length=50)),
                ('elevator_subtitle', models.TextField(null=True)),
                ('direction1_first_train', models.CharField(max_length=50, null=True)),
                ('direction1_last_train', models.CharField(max_length=50, null=True)),
                ('direction2_first_train', models.CharField(max_length=50, null=True)),
                ('direction2_last_train', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.SmallIntegerField()),
                ('station_name', models.CharField(max_length=20)),
                ('is_outside', models.BooleanField()),
                ('restroom_location', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=10)),
                ('station_fullname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='navigation.station')),
            ],
        ),
        migrations.CreateModel(
            name='Ramp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.SmallIntegerField()),
                ('station_name', models.CharField(max_length=20)),
                ('ramp_location', models.CharField(max_length=255)),
                ('station_fullname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='navigation.station')),
            ],
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.SmallIntegerField()),
                ('station_name', models.CharField(max_length=20)),
                ('lift_location', models.CharField(max_length=255)),
                ('operation_section', models.CharField(max_length=10)),
                ('station_fullname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='navigation.station')),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.SmallIntegerField()),
                ('station_name', models.CharField(max_length=20)),
                ('elevator_number', models.CharField(max_length=10, unique=True)),
                ('elevator_location', models.CharField(max_length=100)),
                ('operation_section', models.CharField(max_length=10)),
                ('station_fullname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='navigation.station')),
            ],
        ),
    ]
