package com.hungrybrothers.abletotrip.ui.datatype

data class Attraction(
    val id: Int,
    val attractionName: String,
    val attractionSubName: String?,
    val category1: String,
    val category2: String,
    val si: String,
    val gu: String,
    val dong: String,
    val streetNumber: String?,
    val roadName: String?,
    val latitude: Double,
    val longitude: Double,
    val postalCode: String,
    val roadNameAddress: String?,
    val lotNumberAddress: String,
    val contactNumber: String?,
    val homepageUrl: String?,
    val closedDays: String?,
    val operationHours: String?,
    val isFreeParking: Boolean,
    val isPaidParking: Boolean,
    val isEntranceFee: Boolean,
    val isDisabledRestroom: Boolean,
    val isDisabledParking: Boolean,
    val isLargeParking: Boolean,
    val isAudioGuide: Boolean,
    val attractionImage: String?,
)
